라벨링
seungy0/crush_client pull request #53
Opened 2023-05-30 13:04 UTC by Ssoya1105

옷 전체 상의 하의 기타 라벨링

2023-06-03 06:23 UTC, seungy0 requested changes

2023-06-03 06:23 UTC, seungy0 commented on lib/closet/view/closet_page.dart
> +    if (type == '전체') {
창현님. 중복 코드가 너무 많네요.

2023-06-04 03:50 UTC, Ssoya1105 commented on lib/closet/view/closet_page.dart
> +    if (type == '전체') {
해결했습니다 확인해주세요

2023-06-04 05:02 UTC, seungy0 approved these changes

2023-06-04 05:02 UTC, merged